In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import re

In [10]:
temp_df = pd.read_csv("IMDB Dataset.csv", engine='python')


In [11]:
df = temp_df.iloc[:10000]

In [12]:
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [13]:
df.drop_duplicates(inplace=True)

In [22]:
df.iloc[0,0]

df.iloc[0,0] = re.sub(re.compile('<.*?>'), '', df.iloc[0,0])

In [25]:
df.iloc[0,0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wo

In [24]:
re.sub(re.compile('\d'),'',df.iloc[0,0])

"One of the other reviewers has mentioned that after watching just  Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wou

In [26]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [27]:
df['review'] = df['review'].apply(remove_tags)

In [28]:
df['review'] = df['review'].apply(lambda x:x.lower())

In [34]:
import nltk

In [35]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [40]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

,review
0,one reviewers mentioned watching 1 oz episode ...
1,wonderful little production. filming technique...
2,thought wonderful way spend time hot summer we...
3,basically there's family little boy (jake) thi...
4,"petter mattei's ""love time money"" visually stu..."
...,...
9995,"fun, entertaining movie wwii german spy (julie..."
9996,"give break. anyone say ""good hockey movie""? kn..."
9997,movie bad movie. watching endless series bad h...
9998,"movie probably made entertain middle school, e..."


In [41]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [42]:
df['review']

,review
0,one reviewers mentioned watching 1 oz episode ...
1,wonderful little production. filming technique...
2,thought wonderful way spend time hot summer we...
3,basically there's family little boy (jake) thi...
4,"petter mattei's ""love time money"" visually stu..."
...,...
9995,"fun, entertaining movie wwii german spy (julie..."
9996,"give break. anyone say ""good hockey movie""? kn..."
9997,movie bad movie. watching endless series bad h...
9998,"movie probably made entertain middle school, e..."


In [44]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 37.8 MB/s eta 0:00:00


In [45]:
import gensim

In [46]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [50]:
import nltk

In [53]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [54]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))


In [55]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [56]:
model.build_vocab(story)

In [57]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5849493, 6186875)

In [58]:
len(model.wv.index_to_key)

31845

In [59]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [60]:
document_vector(df['review'].values[0])

array([-0.03699884,  0.37909123,  0.17390645, -0.01757437, -0.06872304,
       -0.5651298 ,  0.15573263,  0.82103705, -0.15523157, -0.10141562,
       -0.01336041, -0.5508293 ,  0.02111023,  0.20359366,  0.04490015,
       -0.21632965,  0.13930397, -0.57128084,  0.05489783, -0.69719607,
        0.14272586,  0.04078529,  0.16205122, -0.18125413, -0.21786118,
       -0.08267306, -0.24669139, -0.33242366, -0.32641727,  0.04468748,
        0.3317265 ,  0.01392537,  0.03029625, -0.26406702, -0.22444637,
        0.24475059,  0.02966978, -0.40375292, -0.19008017, -0.7309242 ,
        0.1663626 , -0.34365088, -0.24281459,  0.01012346,  0.44161558,
       -0.20765442, -0.38470402, -0.13103446,  0.1774651 ,  0.293707  ,
        0.08713445, -0.30526024, -0.18621095, -0.13833597, -0.41310123,
        0.04916532,  0.34723127,  0.12087972, -0.3503748 ,  0.05185973,
        0.0172253 ,  0.21082874, -0.13575463, -0.03100451, -0.39203268,
        0.3478074 , -0.06724943,  0.26413396, -0.5864228 ,  0.30

In [61]:
X = []
for doc in df['review'].values:
    X.append(document_vector(doc))

In [62]:
X = np.array(X)

In [63]:
X[0]

array([-0.03699884,  0.37909123,  0.17390645, -0.01757437, -0.06872304,
       -0.5651298 ,  0.15573263,  0.82103705, -0.15523157, -0.10141562,
       -0.01336041, -0.5508293 ,  0.02111023,  0.20359366,  0.04490015,
       -0.21632965,  0.13930397, -0.57128084,  0.05489783, -0.69719607,
        0.14272586,  0.04078529,  0.16205122, -0.18125413, -0.21786118,
       -0.08267306, -0.24669139, -0.33242366, -0.32641727,  0.04468748,
        0.3317265 ,  0.01392537,  0.03029625, -0.26406702, -0.22444637,
        0.24475059,  0.02966978, -0.40375292, -0.19008017, -0.7309242 ,
        0.1663626 , -0.34365088, -0.24281459,  0.01012346,  0.44161558,
       -0.20765442, -0.38470402, -0.13103446,  0.1774651 ,  0.293707  ,
        0.08713445, -0.30526024, -0.18621095, -0.13833597, -0.41310123,
        0.04916532,  0.34723127,  0.12087972, -0.3503748 ,  0.05185973,
        0.0172253 ,  0.21082874, -0.13575463, -0.03100451, -0.39203268,
        0.3478074 , -0.06724943,  0.26413396, -0.5864228 ,  0.30

In [64]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [65]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [66]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [68]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7736604907361042

In [1]:
numbers = [num for num in range(10) if num%2 == 0]

In [2]:
numbers

[0, 2, 4, 6, 8]